name: nf-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v3
        with:
          version: 'latest-everything'

      - name: Setup nf-test
        uses: nf-core/setup-nf-test@v2

      - name: Create Mock Test Inputs
        run: |
          mkdir -p test_data assets
          touch test_data/genome.fa
          touch test_data/genes.gtf
          mkdir -p test_data/star_index


      - name: Run pipeline tests
        run: nf-test test tests/main.nf.test